- hosts: "{{ target }}"
  become: True
  gather_facts: False
  tasks:
  - name: "Wait for port 3333 to be ready"
    local_action: wait_for port=3333 host="{{ ansible_ssh_host }}" state=started connect_timeout=2 timeout=600


- hosts: "{{ target }}"
  become: True
  tasks:
  - name: "install missing package if needed"
    apt: name={{ item }} update_cache=yes
    with_items:
      - curl
      - htop