- hosts: "{{ target }}"
  become: True
  gather_facts: False
  tasks:
  - name: "Wait for port 22 to be ready"
    local_action: wait_for port=22 host="{{ ansible_ssh_host }}"  search_regex=OpenSSH delay=600

- hosts: "{{ target }}"
  become: True
  tasks:
  - name: "install missing package if needed"
    apt: name={{ item }} update_cache=yes
    with_items:
      - curl
      - htop