- hosts: cluster
  become: True
  gather_facts: False
  tasks:
  - name: "Wait for port 3333 to be ready"
    local_action: wait_for port=3333 host="{{ inventory_hostname }}" state=started connect_timeout=2 timeout=600


- hosts: front
  become: True
  vars_files:
    - vars/main.yml
  pre_tasks:
    - name: "Create root prestashop directory for archive"
      file: path="{{ documentroot }}" state=directory mode="u=rwx,g=rx,o=rx" owner="{{ prestashop_owner }}" group="{{ prestashop_group }}"
    
    - name: "Install missing package if needed"
      apt: name={{ item }} update_cache=yes
      with_items:
        - unzip
        
    - name: Create dynamic MySQL variables.
      set_fact:
        mysql_replication_master: "{{ groups['master'][0] }}"
  
      
  roles:
    - { role: geerlingguy.apache }
    - { role: geerlingguy.php }
    - { role: geerlingguy.apache-php-fpm  }
    - { role: carlosbuenosvinos.ansistrano-deploy }

  post_tasks:
    - name: "Change files permission on {{ documentroot }}" 
      file: dest="{ documentroot }}" state=directory 
            owner="{{ prestashop_owner }}" group="{{ prestashop_group }}"
            recurse=yes
            
- hosts: back
  become: True
  vars_files:
    - vars/main.yml
    
  roles:
    - { role: geerlingguy.mysql }  

- hosts: cluster
  become: True
  gather_facts: False    
  tasks:
  - name: "Install missing package if needed"
    apt: name={{ item }} update_cache=yes
    with_items:
      - htop